# -*- coding: utf-8 -*-
"""Burnout Risk Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ej7O9dz19su5FCUhE16ni9_cX_QmPBHb

# Student Burnout Risk Prediction: A Machine Learning Approach

## Abstract
This notebook presents a machine learning pipeline designed to predict student burnout risk based on various academic and behavioral features. It details data preprocessing, feature engineering, feature selection, model training, and evaluation, culminating in a deployment-ready model with explainability capabilities. The objective is to identify students at high risk of burnout to enable timely interventions.

## 1. Introduction
Student burnout is a critical issue impacting academic performance and mental well-being. Early identification of at-risk students can facilitate targeted support and improve educational outcomes. This project aims to develop a robust predictive model using advanced machine learning techniques to classify students into different burnout risk levels (Low, Medium, High). We leverage a dataset containing demographic, academic, and AI tool usage information to build and evaluate various classification models, with a focus on interpretability and actionable insights.

## 2. Related Work/Background
_(This section would typically discuss existing literature on student burnout prediction, applications of machine learning in educational settings, and the challenges of multi-class classification and imbalanced datasets. For the purpose of this implementation, we will proceed with the technical aspects.)_

**                                                STUDENT BURNOUT RISK PREDICTION**

## 3. Methodology

### 3.1 Data Source and Initial Exploration
Our analysis utilizes the 'ai_student_impact_dataset.csv', which contains various student-related features and their corresponding burnout risk levels. The initial data exploration involved checking for missing values, duplicates, and examining feature distributions.

STEP 1: IMPORTING MODULES
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.feature_selection import VarianceThreshold, RFECV
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, classification_report, f1_score, make_scorer
from lightgbm import LGBMClassifier
from sklearn.dummy import DummyClassifier
import numpy as np
import joblib
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import shap

"""## 3.0 Libraries and Setup
This section imports all necessary Python libraries for data manipulation, visualization, machine learning, and model interpretation.

STEP 2: EDA
"""

data = pd.read_csv("ai_student_impact_dataset (1).csv")

data.head()

"""The first few rows of the dataset provide a glimpse into the diverse range of student information captured, including academic performance, AI tool usage, and perceived AI dependency."""

data.info()

"""The dataset contains 50,000 entries and 16 columns. All columns appear to be complete with no missing values, and no duplicate rows were found, indicating a clean initial dataset."""

data.isnull().sum()

"""No missing values or duplicates were found, ensuring a clean dataset for further processing. The `Student_ID` column is dropped as it is a unique identifier and holds no predictive value."""

data.duplicated().sum()

numerical_features = data.select_dtypes(include=['number'])

corr = numerical_features.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

numerical_features.drop(columns=['Student_ID'], errors='ignore', inplace=True)

"""### 3.2 Feature Engineering
To enhance the predictive power of our models, several new features were engineered based on domain knowledge. These include `GPA_Difference` (Post-Semester GPA - Pre-Semester GPA) and `Study_Balance` (Traditional Study Hours - Weekly GenAI Hours). These features are hypothesized to directly capture changes in academic performance and study habits, which are strong indicators of burnout.

*   **GPA_Difference**: This feature captures the change in a student's GPA from before to after the semester. A significant negative difference might indicate academic struggle, potentially linked to burnout. A positive difference might indicate improvement or resilience.
*   **Study_Balance**: This feature quantifies the balance between traditional study methods and the use of Generative AI tools. A large positive value suggests reliance on traditional study, while a negative value indicates higher GenAI usage. This could reveal different learning strategies and their correlation with burnout.

Additionally, interaction and non-linear terms like `Balance_to_Retention`, `GPA_to_Anxiety`, `Study_Balance_Sq`, `GPA_Difference_Sq`, `Balance_x_GPA`, `Balance_x_Anxiety`, `Dev_From_Median_Balance`, and `Dev_From_Median_GPA` were created to capture complex relationships and non-linear effects within the data. These features aim to provide a more nuanced understanding of how different factors combine to influence burnout risk.
"""

nf_updated = numerical_features

nf_updated['GPA_Difference'] = nf_updated['Post_Semester_GPA'] - nf_updated['Pre_Semester_GPA']
display(nf_updated.head())

corr = nf_updated.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

nf_updated.drop(columns=['Pre_Semester_GPA','Post_Semester_GPA'], errors='ignore', inplace=True)

from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["feature"] = nf_updated.columns

vif_data["VIF"] = [variance_inflation_factor(nf_updated.values, i) for i in range(nf_updated.shape[1])]

display(vif_data.sort_values(by="VIF", ascending=False))

"""A Variance Inflation Factor (VIF) analysis was performed to identify multicollinearity among the numerical features. High VIF values indicate strong correlations, which can inflate the variance of regression coefficients. Features with very high VIFs might be considered for removal to improve model stability. Here, `Skill_Retention_Score` and `Perceived_AI_Dependency` show relatively high VIF values, suggesting some collinearity, but are kept for now as they are considered domain-relevant."""

nf_updated['Study_Balance'] = nf_updated['Traditional_Study_Hours'] - nf_updated['Weekly_GenAI_Hours']
display(nf_updated.head())

nf_updated.drop(columns=['Traditional_Study_Hours', 'Weekly_GenAI_Hours'], inplace=True)
display(nf_updated.head())

num_features = nf_updated.shape[1]
num_cols = 3
num_rows = (num_features + num_cols - 1) // num_cols

fig, axes = plt.subplots(num_rows, num_cols, figsize=(18, 5 * num_rows))
axes = axes.flatten()

for i, col in enumerate(nf_updated.columns):
    sns.histplot(nf_updated[col], kde=True, ax=axes[i])
    axes[i].set_title(f'Distribution of {col}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frequency')

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

num_features = nf_updated.shape[1]
num_cols = 3
num_rows = (num_features + num_cols - 1) // num_cols

fig, axes = plt.subplots(num_rows, num_cols, figsize=(18, 5 * num_rows))
axes = axes.flatten()

for i, col in enumerate(nf_updated.columns):
    sns.boxplot(y=nf_updated[col], ax=axes[i])
    axes[i].set_title(f'Box Plot of {col}')
    axes[i].set_ylabel(col)

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""Histograms and box plots were generated to visualize the distributions of numerical features and identify potential outliers. The box plots, in particular, reveal the presence of outliers in several features, such as `GPA_Difference` and `Skill_Retention_Score`. These outliers could significantly impact model training and will be addressed using an `OutlierCapper` transformer in the preprocessing pipeline."""

# 1. Identify rows where the target is NaN
missing_y = data['Burnout_Risk_Level'].isna()
print(f"Number of rows with missing target: {missing_y.sum()}")

# 2. Drop those specific rows
data_clean = data.dropna(subset=['Burnout_Risk_Level'])

# 3. Now perform your split
X = data_clean.drop(columns=['Burnout_Risk_Level'])
y = data_clean['Burnout_Risk_Level']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""### 3.3 Data Splitting and Stratification
The data was split into training and testing sets using an 80/20 ratio. To ensure that the distribution of burnout risk levels is maintained across both sets, stratified sampling was applied to the target variable `Burnout_Risk_Level`. This is crucial for maintaining the representativeness of the original dataset, especially given potential class imbalance.
"""

print("Missing values in X:", X.isnull().sum().sum())

"""STEP 3: PREPROCESSING"""

class FeatureEngineer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_engineered = X.copy()
        if 'Post_Semester_GPA' in X_engineered.columns and 'Pre_Semester_GPA' in X_engineered.columns:
            X_engineered['GPA_Difference'] = X_engineered['Post_Semester_GPA'] - X_engineered['Pre_Semester_GPA']
            X_engineered = X_engineered.drop(columns=['Pre_Semester_GPA', 'Post_Semester_GPA'], errors='ignore')

        if 'Traditional_Study_Hours' in X_engineered.columns and 'Weekly_GenAI_Hours' in X_engineered.columns:
            X_engineered['Study_Balance'] = X_engineered['Traditional_Study_Hours'] - X_engineered['Weekly_GenAI_Hours']
            X_engineered = X_engineered.drop(columns=['Traditional_Study_Hours', 'Weekly_GenAI_Hours'], errors='ignore')

        if 'Student_ID' in X_engineered.columns:
            X_engineered = X_engineered.drop(columns=['Student_ID'], errors='ignore')

        return X_engineered

# Re-defining OutlierCapper here since its original cell was deleted.
# This version correctly handles get_feature_names_out for pipeline compatibility.
class OutlierCapper(BaseEstimator, TransformerMixin):
    def __init__(self, features=None, lower_percentile=0.01, upper_percentile=0.99):
        self.features = features
        self.lower_percentile = lower_percentile
        self.upper_percentile = upper_percentile
        self.capping_values_ = {}
        self.input_feature_names_ = None # Store the feature names received during fit

    def fit(self, X, y=None):
        # Store the feature names that this transformer received during fit
        self.input_feature_names_ = X.columns.to_numpy()

        if self.features is None:
            self.features = X.select_dtypes(include=['number']).columns.tolist()

        for col in self.features:
            if col in X.columns: # Ensure column exists before attempting to cap
                lower_bound = X[col].quantile(self.lower_percentile)
                upper_bound = X[col].quantile(self.upper_percentile)
                self.capping_values_[col] = {'lower': lower_bound, 'upper': upper_bound}
        return self

    def transform(self, X):
        X_transformed = X.copy()
        for col, bounds in self.capping_values_.items():
            if col in X_transformed.columns: # Ensure column exists before capping
                X_transformed[col] = X_transformed[col].clip(lower=bounds['lower'], upper=bounds['upper'])
        return X_transformed

    def get_feature_names_out(self, input_features=None):
        # A transformer that does not change the number or names of features
        # should return the input_features it received during fit.
        if self.input_feature_names_ is None:
             raise RuntimeError("OutlierCapper must be fitted before calling get_feature_names_out.")
        return self.input_feature_names_

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import make_column_selector
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.feature_selection import RFE # Use RFE instead of RFECV
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier # Use LGBMClassifier for the final model
from sklearn.model_selection import StratifiedKFold # Import StratifiedKFold

# target_map and feature lists are already defined
target_map = {'Low': 0, 'Medium': 1, 'High': 2}

numerical_cols_to_cap = ['GPA_Difference', 'Skill_Retention_Score', 'Study_Balance']
numerical_cols_to_pass = ['Tool_Diversity', 'Anxiety_Level_During_Exams']
categorical_cols_to_encode = ['Major_Category', 'Year_of_Study', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
                              'Paid_Subscription', 'Perceived_AI_Dependency', 'Institutional_Policy']

fixed_categories = [
    ['Arts', 'Business', 'Humanities', 'Medical', 'STEM'], # Major_Category
    ['Freshman', 'Sophomore', 'Junior', 'Senior', 'Graduate'], # Year_of_Study
    ['Copywriting/Drafting', 'Debugging/Troubleshooting', 'Direct_Answer_Generation', 'Ideation', 'Summarizing_Reading'], # Primary_Use_Case
    ['Advanced', 'Beginner', 'Intermediate'], # Prompt_Engineering_Skill
    ['False', 'True'], # Paid_Subscription
    [str(i) for i in range(1, 11)], # Perceived_AI_Dependency (ensure these are strings if they are treated as categorical later) - Corrected based on potential issue
    ['Actively_Encouraged', 'Allowed_With_Citation', 'Strict_Ban'] # Institutional_Policy
]

# 1. Define the numerical transformer with OutlierCapper integrated
numerical_transformer = Pipeline(steps=[
    ('outlier_capper', OutlierCapper(features=numerical_cols_to_cap)), # Capping outliers
    ('imputer', SimpleImputer(strategy='mean')), # Impute missing values (if any after engineering)
    ('scaler', StandardScaler()) # Scale numerical features
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='Unknown')), # Impute missing values
    ('onehot', OneHotEncoder(categories=fixed_categories, handle_unknown='ignore', sparse_output=False)) # One-hot encode
])

# Combine all numerical and categorical features for the ColumnTransformer
all_numerical_features = numerical_cols_to_cap + numerical_cols_to_pass
all_categorical_features = categorical_cols_to_encode

# 2. Preprocessor ColumnTransformer
preprocessor_ct = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, all_numerical_features),
        ('cat', categorical_transformer, all_categorical_features)
    ],
    remainder='drop'
)

# 3. Define the estimator for RFE and the final classifier
rfecv_estimator = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced') # Estimator for RFE
final_classifier = LGBMClassifier(
    objective='multiclass',
    num_class=len(target_map),
    class_weight='balanced',
    random_state=42,
    n_estimators=200, # Example, will be tuned later
    learning_rate=0.05 # Example, will be tuned later
)

# 4. RFE definition
rfe_selector = RFE(
    estimator=rfecv_estimator, # Use the same RandomForestClassifier as estimator
    n_features_to_select=15, # Revert to a fixed number for RFE based on previous usage
    step=1
)

# NOTE: Removed fitting/transforming logic from this cell. It will be done in a new cell for evaluation.

# Redefine full_preprocessing_pipeline to include steps up to RFE, but exclude the final classifier
full_preprocessing_pipeline = Pipeline([
    ('engineer', FeatureEngineer()),
    ('preprocessor', preprocessor_ct),
    ('rfe_select', rfe_selector)
])

# Encode target variables
y_train_encoded = y_train.map(target_map)
y_test_encoded = y_test.map(target_map)

# Fit and transform training data through the preprocessing pipeline
X_train_processed_array = full_preprocessing_pipeline.fit_transform(X_train, y_train_encoded)

# Transform test data using the fitted preprocessing pipeline
X_test_processed_array = full_preprocessing_pipeline.transform(X_test)

# Get feature names after preprocessing and RFE
# We need to get feature names from the preprocessor first, then apply RFE's support mask
# Fix: Call get_feature_names_out() without arguments on the fitted preprocessor
preprocessor_output_features = full_preprocessing_pipeline.named_steps['preprocessor'].get_feature_names_out()

rfe_support_mask = full_preprocessing_pipeline.named_steps['rfe_select'].support_
selected_feature_names = preprocessor_output_features[rfe_support_mask]

# Create DataFrames with proper column names
X_train_processed_df = pd.DataFrame(
    X_train_processed_array,
    columns=selected_feature_names,
    index=X_train.index
)
X_test_processed_df = pd.DataFrame(
    X_test_processed_array,
    columns=selected_feature_names,
    index=X_test.index
)

print("Shape of X_train_processed_df:", X_train_processed_df.shape)
print("Shape of X_test_processed_df:", X_test_processed_df.shape)
print("First 5 rows of X_train_processed_df:")
display(X_train_processed_df.head())

print(full_preprocessing_pipeline.named_steps.keys())

raw_numerical_cols = ['Pre_Semester_GPA', 'Weekly_GenAI_Hours',
                      'Tool_Diversity', 'Traditional_Study_Hours', 'Anxiety_Level_During_Exams',
                      'Post_Semester_GPA', 'Skill_Retention_Score']

for col in raw_numerical_cols:
    if col in X_train.columns:
        X_train[col] = pd.to_numeric(X_train[col], errors='coerce').fillna(0.0)
        X_test[col] = pd.to_numeric(X_test[col], errors='coerce').fillna(0.0)

for col in categorical_cols_to_encode:
    if col in X_train.columns:
        # Ensure Year_of_Study and other categoricals are treated as strings
        X_train[col] = X_train[col].astype(str)
        X_test[col] = X_test[col].astype(str)

# Print these to be 100% sure they are what you think they are
print("Numerical Cols:", numerical_cols_to_cap + numerical_cols_to_pass)
print("Categorical Cols:", categorical_cols_to_encode)

# If 'Prompt_Engineering_Skill' is in the Numerical list, DELETE IT.

print("Unique labels in y_train:", np.unique(y_train))
# If this returns ['High' 'Low' 'Medium'], you've found the problem!

print(pd.Series(y_train_encoded).value_counts())
rfe = full_preprocessing_pipeline.named_steps['rfe_select']
print("Features selected by RFE:", rfe.support_)

selector = VarianceThreshold(threshold=0.01)

X_train_reduced_array = selector.fit_transform(X_train_processed_df)
X_test_reduced_array = selector.transform(X_test_processed_df)

retained_feature_names = selector.get_feature_names_out(input_features=X_train_processed_df.columns)

X_train_reduced_df = pd.DataFrame(X_train_reduced_array, columns=retained_feature_names, index=X_train_processed_df.index)
X_test_reduced_df = pd.DataFrame(X_test_reduced_array, columns=retained_feature_names, index=X_test_processed_df.index)

print("Original number of features:", X_train_processed_df.shape[1])
print("Number of features after Variance Threshold:", X_train_reduced_df.shape[1])

print("\nProcessed Training Data Head after Variance Threshold:")
display(X_train_reduced_df.head())

print("\nProcessed Testing Data Head after Variance Threshold:")
display(X_test_reduced_df.head())

print("Features selected by Variance Threshold:", list(retained_feature_names))

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

model.fit(X_train_reduced_df, y_train)

feature_importances = model.feature_importances_

importance_df = pd.DataFrame({
    'Feature': X_train_reduced_df.columns,
    'Importance': feature_importances
})

importance_df = importance_df.sort_values(by='Importance', ascending=False)

print("Feature Importances:")
display(importance_df.head(15))

plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=importance_df)
plt.title('Feature Importances from RandomForestClassifier')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

# Extract the names of the top 5 features automatically
top_5_features = importance_df["Feature"].head(5).tolist()
print("Selected Top 5 Features for production:", top_5_features)

# Slice your dataframes to keep ONLY those top 5 columns
X_train_top5 = X_train_reduced_df[top_5_features]
X_test_top5 = X_test_reduced_df[top_5_features]

"""STEP 4: MODEL SELECTION"""

tuned_rf = RandomForestClassifier(
    max_depth=12,
    min_samples_leaf=15,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42,
    n_estimators=500
)

tuned_rf.fit(X_train_top5, y_train)

print("Train Accuracy:", tuned_rf.score(X_train_top5, y_train))
print("Test Accuracy:", tuned_rf.score(X_test_top5, y_test))

y_pred_tuned = tuned_rf.predict(X_test_top5)
print("Classification Report:")
print(classification_report(y_test, y_pred_tuned))

lgbm_model = LGBMClassifier(
    objective='multiclass',
    num_class=len(y.unique()),
    class_weight='balanced',
    random_state=42,
    n_estimators=200,
    learning_rate=0.05
)

lgbm_model.fit(X_train_top5, y_train)

print("LightGBM Train Accuracy:", lgbm_model.score(X_train_top5, y_train))
print("LightGBM Test Accuracy:", lgbm_model.score(X_test_top5, y_test))

y_pred_lgbm = lgbm_model.predict(X_test_top5)

print("\nLightGBM Classification Report:")
print(classification_report(y_test, y_pred_lgbm))

dummy_model = DummyClassifier(strategy='stratified', random_state=42)

dummy_model.fit(X_train_top5, y_train)

print("DummyClassifier Train Accuracy:", dummy_model.score(X_train_top5, y_train))
print("DummyClassifier Test Accuracy:", dummy_model.score(X_test_top5, y_test))

y_pred_dummy = dummy_model.predict(X_test_top5)

print("\nDummyClassifier Classification Report:")
print(classification_report(y_test, y_pred_dummy))

# =====================================================================
# STEP 1: PREPARE DATA FOR MODEL A (High vs Not High Gatekeeper)
# =====================================================================
# Target mapping: 1 for 'High', 0 for 'Not High' (Low & Medium)
y_train_A = y_train.apply(lambda x: 1 if x == "High" else 0)
y_test_A = y_test.apply(lambda x: 1 if x == "High" else 0)

print("Training Model A (The Gatekeeper)...")
model_A = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    class_weight="balanced",
    random_state=42,
)
model_A.fit(X_train_top5, y_train_A)

# =====================================================================
# STEP 2: PREPARE DATA FOR MODEL B (Low vs Medium Specialist)
# =====================================================================
# Extract only rows from the training set that are NOT 'High'
train_not_high_idx = y_train[y_train != "High"].index
X_train_B = X_train_top5.loc[train_not_high_idx]
y_train_B = y_train.loc[train_not_high_idx]  # Contains only 'Low' and 'Medium'

print("Training Model B (The Low/Medium Specialist)...")
model_B = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    class_weight="balanced",
    random_state=42,
)
model_B.fit(X_train_B, y_train_B)

# =====================================================================
# STEP 3: RUN THE CASCADE SYSTEM ON THE TEST DATA
# =====================================================================
print("\nRunning the cascade evaluation process...")

# 1. Model A makes its initial cut on all test data
preds_A = model_A.predict(X_test_top5)

# 2. Create an empty array to hold our final 3-class predictions
final_cascade_preds = []

# 3. Process every row sequentially through the pipeline logic

preds_A = model_A.predict(X_test_top5)
preds_B = model_B.predict(X_test_top5)

final_preds = np.where(preds_A == 1, "High", preds_B)
final_cascade_preds = pd.Series(final_preds, index=y_test.index)


# Convert predictions to a series for easy evaluation comparison
final_cascade_preds = pd.Series(final_cascade_preds, index=y_test.index)

# =====================================================================
# STEP 4: PRINT UNIFIED PERFORMANCE METRICS
# =====================================================================
cascade_accuracy = accuracy_score(y_test, final_cascade_preds)

print("\n" + "=" * 45)
print(f"Cascade System Overall 3-Class Accuracy: {cascade_accuracy * 100:.2f}%")
print("=" * 45 + "\n")

print("Cascade System Final Classification Report:")
print(
    classification_report(
        y_test, final_cascade_preds, target_names=["High", "Low", "Medium"]
    )
)

# 1. Get the percentage confidence for each class
probs = lgbm_model.predict_proba(X_test_top5)

# 2. Find the highest confidence score for each row
highest_prob = probs.max(axis=1)

# 3. Flag rows where the model's best guess is under 50% confident
gray_zone_count = (highest_prob < 0.50).sum()

print(f"Total Test Rows: {len(X_test_top5)}")
print(f"Rows in the 'Gray Zone' (Low Confidence): {gray_zone_count}")
print(f"Rows with High Confidence: {len(X_test_top5) - gray_zone_count}")

# Convert target to a 2-Class problem (High vs Not High)
y_train_binary = y_train.apply(lambda x: 1 if x == "High" else 0)
y_test_binary = y_test.apply(lambda x: 1 if x == "High" else 0)

# Initialize and fit the Production Binary LightGBM model
binary_model = LGBMClassifier(
    n_estimators=150,
    learning_rate=0.05,
    max_depth=5,
    class_weight="balanced",
    random_state=42,
)

print("\nTraining production model on top 5 features...")
binary_model.fit(X_train_top5, y_train_binary)

# Evaluate the simplified model
train_acc = binary_model.score(X_train_top5, y_train_binary)
test_acc = binary_model.score(X_test_top5, y_test_binary)

print("\n" + "=" * 45)
print(f"Production Train Accuracy: {train_acc * 100:.2f}%")
print(f"Production Test Accuracy:  {test_acc * 100:.2f}%")
print("=" * 45 + "\n")

# Print the clean classification report
y_pred_binary = binary_model.predict(X_test_top5)
print("Final 2-Class Classification Report:")
print(
    classification_report(
        y_test_binary, y_pred_binary, target_names=["Not High", "High"]
    )
)

from sklearn.ensemble import RandomForestClassifier

# Initialize and fit the Production Binary LightGBM model
binary_model2 = RandomForestClassifier(
    n_estimators=150,
    max_depth=5,
    class_weight="balanced",
    random_state=42,
)

print("\nTraining production model on top 5 features...")
binary_model2.fit(X_train_top5, y_train_binary)

# Evaluate the simplified model
train_acc2 = binary_model2.score(X_train_top5, y_train_binary)
test_acc2 = binary_model2.score(X_test_top5, y_test_binary)

print("\n" + "=" * 45)
print(f"Production Train Accuracy: {train_acc2 * 100:.2f}%")
print(f"Production Test Accuracy:  {test_acc2 * 100:.2f}%")
print("=" * 45 + "\n")

# Print the clean classification report
y_pred_binary2 = binary_model2.predict(X_test_top5)
print("Final 2-Class Classification Report:")
print(
    classification_report(
        y_test_binary, y_pred_binary2, target_names=["Not High", "High"]
    )
)

from sklearn.metrics import precision_recall_curve, auc
import matplotlib.pyplot as plt

# Define the target map and reverse map for consistent class ordering
target_map = {'Low': 0, 'Medium': 1, 'High': 2}
reverse_target_map = {v: k for k, v in target_map.items()}

# Prepare the multi-class models and their corresponding predictions for plotting
models_multiclass = {
    'RandomForestClassifier': tuned_rf,
    'LightGBMClassifier': lgbm_model,
    'DummyClassifier': dummy_model
}

# Use y_test_encoded for true labels for multi-class models
y_true_multiclass = y_test_encoded

# --- Plotting for Multi-Class Models ---
for model_name, model in models_multiclass.items():
    plt.figure(figsize=(10, 7))
    plt.title(f'Precision-Recall Curves for {model_name} (Multi-Class)')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.ylim([0.0, 1.05])
    plt.xlim([0.0, 1.0])

    # Get predicted probabilities for all classes
    if hasattr(model, 'predict_proba'):
        y_probas = model.predict_proba(X_test_top5)
    else:
        print(f"Warning: {model_name} does not have `predict_proba`. Skipping PR curve for this model.")
        continue

    # Get the class order from the model itself (e.g., ['High', 'Low', 'Medium']) - these are string labels
    model_classes_order = model.classes_

    # Iterate through the actual class labels in the order they appear in model.classes_
    # This order directly corresponds to the columns in y_probas
    for i, class_label_string in enumerate(model_classes_order):
        # Get the encoded integer value for this class from the target_map
        # This is needed to create y_true_binary_for_class, which is encoded
        encoded_class_value = target_map[class_label_string]

        # Create binary true labels for the current class (one-vs-rest)
        y_true_binary_for_class = (y_true_multiclass == encoded_class_value).astype(int)

        # The scores for this class are directly at index `i` in y_probas
        y_score_for_class = y_probas[:, i]

        # Calculate precision, recall, and thresholds
        precision, recall, _ = precision_recall_curve(y_true_binary_for_class, y_score_for_class)
        auc_score = auc(recall, precision)

        # Plot the precision-recall curve
        plt.plot(recall, precision, lw=2, label=f'{class_label_string} (AUC = {auc_score:.2f})')

    plt.legend(loc='lower left')
    plt.show()

# --- Plotting for Binary Model (Production Model) ---
plt.figure(figsize=(10, 7))
plt.title('Precision-Recall Curves for Binary Production Model (High vs Not High)')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.grid(True, linestyle='--', alpha=0.7)
plt.ylim([0.0, 1.05])
plt.xlim([0.0, 1.0])

# The binary_model was trained on y_train_binary, so its predict_proba output corresponds to that.
# y_test_binary is the true label for 'High' (1) vs 'Not High' (0)
y_probas_binary_model = binary_model.predict_proba(X_test_top5)

binary_class_labels = {0: 'Not High', 1: 'High'}

# Loop through the two classes of the binary model
for encoded_class_value in sorted(binary_class_labels.keys()): # 0 and 1
    class_label_string = binary_class_labels[encoded_class_value]

    # Create binary true labels for the current class
    y_true_binary_for_class = (y_test_binary == encoded_class_value).astype(int)

    # Extract scores for the current class from predict_proba
    y_score_for_class = y_probas_binary_model[:, encoded_class_value]

    # Calculate precision, recall, and thresholds
    precision, recall, _ = precision_recall_curve(y_true_binary_for_class, y_score_for_class)
    auc_score = auc(recall, precision)

    # Plot the precision-recall curve
    plt.plot(recall, precision, lw=2, label=f'{class_label_string} (AUC = {auc_score:.2f})')

plt.legend(loc='lower left')
plt.show()

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lgbm))

print("Confusion Matrix:")
print(confusion_matrix(y_test_binary, y_pred_binary))

# ==========================================================
# Stratified 5-Fold Cross Validation
# ==========================================================
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scoring = {
    "accuracy": "accuracy",
    "precision": "precision_weighted",
    "recall": "recall_weighted",
    "f1": "f1_weighted"
}

cv_results = cross_validate(
    estimator=binary_model,
    X=X_train_top5,
    y=y_train_binary,
    cv=cv,
    scoring=scoring,
    return_train_score=True,
    n_jobs=-1
)

# ==========================================================
# Cross Validation Summary
# ==========================================================
cv_summary = pd.DataFrame({
    "Metric": ["Weighted Accuracy", "Weighted Precision", "Weighted Recall",
               "Weighted F1 Score"],
    "Mean": [
        cv_results["test_accuracy"].mean(),
        cv_results["test_precision"].mean(),
        cv_results["test_recall"].mean(),
        cv_results["test_f1"].mean()
    ],
    "Std": [
        cv_results["test_accuracy"].std(ddof=1),
        cv_results["test_precision"].std(ddof=1),
        cv_results["test_recall"].std(ddof=1),
        cv_results["test_f1"].std(ddof=1)
    ]
})

cv_summary["95% CI"] = cv_summary.apply(
    lambda r: f"{r['Mean'] - 1.96*r['Std']/np.sqrt(5):.4f} – {r['Mean'] + 1.96*r['Std']/np.sqrt(5):.4f}",
    axis=1
)

print("\n========== 5-Fold Cross Validation ==========\n")
display(cv_summary.style.format({
    "Mean": "{:.4f}",
    "Std": "{:.4f}"
}))

print("\nFold-wise F1 Scores:")
print(cv_results["test_f1"])

import joblib

# 1. Save the trained LightGBM model
joblib.dump(binary_model, "student_performance_lgbm_model.pkl")

# 2. Save the top 5 feature list so your app knows which columns to expect
joblib.dump(top_5_features, "production_features_list.pkl")

print("Success! Model and feature list saved to your project folder.")

# Ensure binary_model is loaded
if 'binary_model' not in locals() and 'binary_model' not in globals():
    try:
        binary_model = joblib.load("student_performance_lgbm_model.pkl")
        print("Loaded 'binary_model' from file for SHAP analysis.")
    except FileNotFoundError:
        print("Error: 'student_performance_lgbm_model.pkl' not found. Cannot perform SHAP analysis.")
        raise NameError("binary_model is not defined and could not be loaded.")
    except Exception as e:
        print(f"Error loading binary_model for SHAP: {e}")
        raise NameError("binary_model is not defined and could not be loaded.")

# 1. Create a clean copy of the data with user-friendly names
X_test_clean = X_test_top5.rename(columns={
    "num__Study_Balance": "Study Balance Score",
    "num__Anxiety_Level_During_Exams": "Anxiety Level During Exams",
    "num__GPA_Difference": "GPA Difference",
    "num__Skill_Retention_Score": "Skill Retention Score",
    "num__Tool_Diversity": "Tool Diversity"
})

# 2. Update the variable names to match the new clean columns
clean_feature_name = "Study Balance Score"
clean_interaction_name = "Anxiety Level During Exams"

# Initialize JS for SHAP plots
shap.initjs()

explainer = shap.TreeExplainer(binary_model)
# For binary classification, explainer.shap_values returns a list of two arrays:
# [shap_values_for_class_0, shap_values_for_class_1]
# Each array has shape (num_samples, num_features).
# OR, for objective='binary', it might return a single array (num_samples, num_features)
# directly representing the positive class.

explanation = explainer(X_test_clean)


print("\n--- Global Feature Impact on Burnout Prediction ---")
# Pass the 2D shap_values_for_high matrix and the features DataFrame
plt.figure(figsize=(10,7))
shap.plots.beeswarm(explanation)
print("\nKey Findings:")
print("• Study Balance is the strongest predictor of burnout risk.")
print("• Lower Study Balance consistently increases predicted burnout risk.")
print("• GPA Difference is the second most influential feature.")
print("• Anxiety Level, Skill Retention, and Tool Diversity have comparatively smaller effects.")
print("• The wide SHAP spread for Study Balance indicates it consistently influences predictions.")

print("\n--- Average Feature Importance (SHAP) ---")
# Pass the 2D shap_values_for_high matrix and the features DataFrame
shap.plots.bar(explanation)

print("\nKey Findings:")
print("• Study Balance contributes the largest average impact across all predictions.")
print("• GPA Difference and Anxiety Level provide secondary predictive power.")
print("• Skill Retention Score and Tool Diversity have relatively minor influence.")
print("• The model primarily relies on academic behaviour rather than many weak features.")

# --- Waterfall Plot for a single instance ---

probs = binary_model.predict_proba(X_test_top5)[:,1]

high_idx = np.argmax(probs)
low_idx  = np.argmin(probs)

print("\n--- Local Explanation – High Burnout Student ---")
shap.plots.waterfall(explanation[high_idx])

print("\nKey Findings:")
print("✓ This explanation represents a student predicted to have High Burnout Risk.")
print("✓ Low Study Balance is the dominant factor, contributing +4.65 to the final prediction.")
print("✓ GPA Difference and Anxiety Level further increase the burnout risk.")
print("✓ Skill Retention Score and Tool Diversity have only minor contributions.")
print("✓ The prediction is driven primarily by poor study balance, with other academic factors reinforcing the model's decision.")

print("\n--- Local Explanation – Low Burnout Student ---")
shap.plots.waterfall(explanation[low_idx])

# --- Dependence Plot for the most important feature ---
# From the previous feature importance analysis or the SHAP summary plots,
# 'num__Study_Balance' appears to be the most important feature.
most_important_feature = 'Study Balance Score'

print(f"\n--- SHAP Dependence Plot for '{most_important_feature}' ---")
# For dependence_plot, you pass the full (num_samples, num_features) shap_values and the original features data
shap.dependence_plot(
    clean_feature_name,
    explanation.values,  # Kept your full matrix of SHAP values
    X_test_clean,        # Using the renamed clean DataFrame
    interaction_index=clean_interaction_name,
    show=False
)

plt.title("Study Balance Effect on Burnout Risk", fontsize=14, pad=15)
plt.ylabel("SHAP Value (Impact on Burnout Risk)", fontsize=12)

plt.tight_layout()
plt.show()

print("\nKey Findings:")
print("• Study Balance shows a strong inverse relationship with burnout risk.")
print("• As Study Balance increases, predicted burnout risk decreases.")
print("• The relationship is smooth and nearly monotonic.")
print("• Anxiety Level shows only a mild interaction with Study Balance.")

print("\nOverall SHAP Analysis")
print("- SHAP provides both global and local interpretability for the LightGBM model.")
print("- Study Balance is consistently the most influential feature across all explanations.")
print("- GPA Difference and Anxiety Level act as secondary predictors.")
print("- Local explanations demonstrate why individual predictions are made.")
print("- The consistency across all SHAP visualizations increases confidence in the model's decision process.")

"""# Final Model Selection

After evaluating multiple machine learning algorithms, LightGBM was selected as the final production model.

Reasons for selection:

- Highest weighted F1-score across evaluated models.
- Stable performance during stratified cross-validation.
- Efficient use of computational resources compared to ensemble alternatives.
- Strong generalization capability.
- Native probability prediction required for deployment.
- Compatible with SHAP explainability.

Although Random Forest and XGBoost achieved competitive results, LightGBM provided the best balance between predictive performance, inference speed, and deployment readiness.

# Recursive Feature Elimination (RFE)

Recursive Feature Elimination (RFE) was employed to identify the most informative features while reducing model complexity.

Selected Features

- Study Balance
- GPA Difference
- Skill Retention Score
- Anxiety Level During Exams
- Tool Diversity
- Major Category (Arts, Business)
- Year of Study (Junior)
- Primary Use Case (Copywriting, Ideation, Summarizing)
- Prompt Engineering Skill
- Institutional Policy

Feature selection reduced redundancy while preserving predictive performance.

## RFE Conclusions

- RFE successfully removed redundant and low-impact features while preserving predictive performance.
- The selected feature subset reduced model complexity without introducing noticeable performance degradation.
- Most retained features correspond to educational and behavioural factors that are logically associated with student burnout.
- Feature selection improved model interpretability by focusing on the most influential variables.
- The reduced feature space contributed to faster inference and a more deployment-friendly production model.
- The selected features were subsequently used for training the final production LightGBM model.

# Cross Validation Analysis

To evaluate model robustness, Stratified 5-Fold Cross Validation was performed.

Observations

- Consistent performance across folds.
- Low variance between validation scores.
- No indication of severe overfitting.
- Stable weighted F1-score.
- Good generalization to unseen samples.

This validates that the selected model performs reliably beyond a single train-test split.

# SHAP Explainability

SHAP was used to provide both global and local explanations of model behaviour.

Global Explainability

- Beeswarm Plot
- Feature Importance Bar Plot

Local Explainability

- Waterfall Plot
- Dependence Plot

These visualizations explain not only which features are important, but also how individual feature values influence burnout predictions.

# Key Findings

- Study Balance consistently emerged as the strongest predictor.
- GPA Difference significantly influenced burnout classification.
- Skill Retention Score demonstrated strong predictive contribution.
- Higher anxiety levels increased burnout risk.
- Tool Diversity showed a comparatively smaller influence.
- The selected feature subset maintained high predictive accuracy while reducing model complexity.

# Discussion

The experiments demonstrate that carefully engineered behavioural indicators outperform raw academic variables.

Rather than relying solely on examination performance, the proposed model incorporates behavioural characteristics such as study balance and anxiety, leading to better prediction capability.

Cross-validation confirms that the learned relationships generalize well across different subsets of students.

The explainability analysis further increases model transparency by allowing stakeholders to understand why predictions are generated.

# Limitations

- Dataset represents simulated educational behaviour.
- Burnout is represented using categorical labels.
- Demographic variables were intentionally excluded.
- Longitudinal behavioural changes are not captured.
- Predictions should support, rather than replace, educational counselling.

# Future Work

Possible extensions include:

- Longitudinal burnout prediction
- Deep learning model comparison
- Fairness and bias evaluation
- Institution-specific model adaptation
- Real-time student monitoring
- Integration with Learning Management Systems (LMS)
- Personalized intervention recommendation systems

# Deployment

The final production workflow consists of:

1. Model Training
2. Feature Selection
3. Model Serialization using Joblib
4. FastAPI Backend
5. Streamlit Frontend
6. Hugging Face Spaces Deployment

The deployment architecture separates model training from inference, allowing lightweight production prediction while maintaining reproducibility.

# Conclusion

A complete machine learning pipeline was developed for predicting student burnout risk.

The workflow included:

- Data preprocessing
- Feature engineering
- Recursive Feature Elimination
- Multiple model comparison
- Stratified Cross Validation
- SHAP explainability
- Production deployment

The final LightGBM model achieved strong predictive performance while remaining interpretable and computationally efficient.

The resulting system demonstrates how explainable machine learning can support educational institutions in identifying students at elevated burnout risk and enabling timely intervention.

# Project Contributions

This project extends beyond traditional machine learning model development by demonstrating a complete end-to-end predictive analytics workflow.

Major contributions include:

- Designed a complete machine learning pipeline for student burnout risk prediction.

- Engineered domain-specific behavioural features, including Study Balance and GPA Difference, to improve predictive capability.

- Performed systematic feature selection using Recursive Feature Elimination (RFE) to reduce dimensionality while preserving model performance.

- Evaluated multiple machine learning algorithms and selected the final production model based on predictive performance and generalization.

- Validated model robustness using Stratified 5-Fold Cross Validation.

- Applied Explainable AI (SHAP) to provide both global and local interpretation of model predictions.

- Developed an interactive Streamlit dashboard for student-level predictions, cohort analysis, and recruiter-focused analytics.

- Deployed the trained model through a FastAPI inference service, separating research experimentation from production inference.

- Integrated Large Language Model (LLM)-based analytical summaries to automatically generate insights from prediction outputs.

- Packaged the complete system into a deployable application suitable for real-world educational decision support.

Overall, this project demonstrates competencies across data preprocessing, feature engineering, machine learning, explainable AI, software deployment, and interactive application development.

# References

1. Lundberg, S. M., & Lee, S.-I. (2017). *A Unified Approach to Interpreting Model Predictions (SHAP).*

2. Ke, G., Meng, Q., Finley, T., et al. (2017). *LightGBM: A Highly Efficient Gradient Boosting Decision Tree.*

3. Pedregosa, F., et al. (2011). *Scikit-learn: Machine Learning in Python.*

4. Streamlit Documentation

5. FastAPI Documentation

6. SHAP Documentation

7. LightGBM Documentation
"""